### ISSUE TITLE
Remove the `joinGroup` function in `index.tsx` file

### ISSUE THREAD

**Issue by vplasencia** [vplasencia/bandada-semaphore-demo#7]

**Comment by zhangdav** [comment]
const providerName = group.credentials.id.split("_")[0].toLowerCase()
    const identityCommitment = _identity?.getCommitment().toString()

    window.open(
      `${process.env.NEXT_PUBLIC_BANDADA_DASHBOARD_URL}/credentials?group=${groupId}&member=${identityCommitment}&provider=${providerName}&redirect_uri=${process.env.NEXT_PUBLIC_APP_URL}`
    )
